In [1]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('../data/listings.csv')
df.head() # prints the first five rows

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340

In [ ]:
df.shape # tells you dimensions of the df. returns tuple with # of rows and # of cols

# print("that was the shape\n\n")

df.info()

# df.info() => gives u class (confirms its a pd df), index range (how many rows/entries, and what index is)
# gives u total col count, gives a table of column details: so it goes horizontally across the header
# and gives you the col number, col name, the non-null count (how many actual values exist -- good to spot MISSING DATA)
# and the Dtype = data type integer, object, float, and finally the memory usage - how much RAM is being used

# df.info() is important to spot missing data, paired with df shape, makes sure 'objects' (text) can be converted to numbers before performing math
# if im working with a massive dataset df.info will tell me how much memory is being hogged

print("\n\nthat was the info \n\n")

df.describe()

# df.describe() gives statistics (the data math)
# shows mean, median, min, max...
# good for "what is the average val in this col"

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46527 entries, 0 to 46526
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              46527 non-null  int64
 1   name                            46509 non-null  object
 2   host_id                         46527 non-null  int64
 3   host_name                       46492 non-null  object
 4   neighbourhood_group             46527 non-null  object
 5   neighbourhood                   46527 non-null  object
 6   latitude                        46527 non-null  float64
 7   longitude                       46527 non-null  float64
 8   room_type                       46527 non-null  object
 9   price                           46527 non-null  int64
 10  minimum_nights                  46527 non-null  int64
 11  number_of_reviews               46527 non-null  int64
 12  last_review                     35816 non-null  object
 13  reviews_per_month               35816 non-null  float64
 14  calculated_host_listings_count  46527 non-null  int64
 15  availability_365                46527 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 5.7+ MB


that was the info

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,4.652700e+04,4.652700e+04,46527.000000,46527.000000,46527.00000,46527.000000,46527.000000,35816.000000,46527.000000,46527.000000
mean,2.299891e+07,8.439186e+07,40.729563,-73.950918,148.60567,8.519634,22.767167,0.905802,5.890451,121.142842
std,1.373123e+07,9.913260e+07,0.054974,0.047562,318.62788,23.050570,46.603900,1.280898,22.731346,142.517750
min,2.595000e+03,2.438000e+03,40.508680,-74.239860,0.00000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,1.062558e+07,9.194284e+06,40.689945,-73.983170,65.00000,2.000000,1.000000,0.120000,1.000000,0.000000
50%,2.220528e+07,3.719496e+07,40.724400,-73.955380,100.00000,3.000000,4.000000,0.380000,1.000000,46.000000
75%,3.575440e+07,1.362274e+08,40.763040,-73.934170,160.00000,6.000000,21.000000,1.210000,2.000000,252.000000
max,4.481801e+07,3.624537e+08,40.911690,-73.712990,10000.00000,1250.000000,746.000000,46.240000,249.000000,365.000000

In [15]:
# from lecture
print(df.shape, len(df))

(46527, 16) 46527

## BASIC SYNTAX

### Select one column

In [19]:
# good for series 
df['name']

df['price']

0        175
1         75
2         60
3        175
4         65
        ...
46522    145
46523     87
46524     59
46525     80
46526     66
Name: price, Length: 46527, dtype: int64

In [23]:
# gives a dataframe -- REMEMBER TO PASS THE COLS AS A LIST
df[["id","name","price"]]

# you could also do
cols = ["id", "name","price"]
df[cols]

             id                                               name  price
0          2595                              Skylit Midtown Castle    175
1          3831  Whole flr w/private bdrm, bath & kitchen(pls r...     75
2          5121                                    BlissArtsSpace!     60
3          5136           Spacious Brooklyn Duplex, Patio + Garden    175
4          5178                   Large Furnished Room Near B'way　     65
...         ...                                                ...    ...
46522  44807522         Designer Gramercy Studio Townhouse by UNSQ    145
46523  44807786  Cozy & comfy apt in the heart of Inwood Manhattan     87
46524  44811717  Comfortable safe environment 24hr security camera     59
46525  44814944                 Upper West Side studio 86th Street     80
46526  44818009  5MIN D/N trains, NEAR THE BEACH, 50’ TO MANHATTAN     66

[46527 rows x 3 columns]

# Selecting ROWS

In [26]:
df.tail() # LAST 10 ROWS

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
46522,44807522,Designer Gramercy Studio Townhouse by UNSQ,12941925,Brian,Manhattan,Gramercy,40.73433,-73.98383,Entire home/apt,145,7,0,NaN,NaN,1,164
46523,44807786,Cozy & comfy apt in the heart of Inwood Manhattan,284790520,Salar,Manhattan,Washington Heights,40.85820,-73.92733,Entire home/apt,87,6,0,NaN,NaN,2,85
46524,44811717,Comfortable safe environment 24hr security camera,362453686,Nicole,Brooklyn,East Flatbush,40.65399,-73.93287,Private room,59,3,0,NaN,NaN,1,90
46525,44814944,Upper West Side studio 86th Street,4039777,Fernando,Manhattan,Upper West Side,40.78731,-73.97029,Entire home/apt,80,30,0,NaN,NaN,1,113
46526,44818009,"5MIN D/N trains, NEAR THE BEACH, 50’ TO MANHATTAN",48098268,Marina,Brooklyn,Gravesend,40.59945,-73.98209,Private room,66,1,0,NaN,NaN,1,38

In [ ]:
# integer location selection
# select data from DF by using numerical indices, like u would in a py list

df.iloc[0:5] # first 5 rows

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
46522,44807522,Designer Gramercy Studio Townhouse by UNSQ,12941925,Brian,Manhattan,Gramercy,40.73433,-73.98383,Entire home/apt,145,7,0,NaN,NaN,1,164
46523,44807786,Cozy & comfy apt in the heart of Inwood Manhattan,284790520,Salar,Manhattan,Washington Heights,40.85820,-73.92733,Entire home/apt,87,6,0,NaN,NaN,2,85
46524,44811717,Comfortable safe environment 24hr security camera,362453686,Nicole,Brooklyn,East Flatbush,40.65399,-73.93287,Private room,59,3,0,NaN,NaN,1,90
46525,44814944,Upper West Side studio 86th Street,4039777,Fernando,Manhattan,Upper West Side,40.78731,-73.97029,Entire home/apt,80,30,0,NaN,NaN,1,113
46526,44818009,"5MIN D/N trains, NEAR THE BEACH, 50’ TO MANHATTAN",48098268,Marina,Brooklyn,Gravesend,40.59945,-73.98209,Private room,66,1,0,NaN,NaN,1,38

In [ ]:
df.iloc[[0,10,100]] # gives you rows 0, 10, and 100

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365
10,6090,West Village Nest - Superhost,11975,Alina,Manhattan,West Village,40.73530,-74.00525,Entire home/apt,65,30,29,2020-07-25,0.22,1,197
100,29628,Sunny Room in New Condo,127608,Chris,Brooklyn,Clinton Hill,40.68414,-73.96351,Private room,89,3,281,2020-02-17,2.26,1,364

In [ ]:
df.loc[14] # selected row 14
# df.loc[] uses the names of rows not numbers
# syntax: df[row_label, col_label]

id                                                                     7750
name                              2 Furnished bedrooms next to Central Park
host_id                                                               17985
host_name                                                              Sing
neighbourhood_group                                               Manhattan
neighbourhood                                                   East Harlem
latitude                                                           40.79685
longitude                                                         -73.94872
room_type                                                      Private room
price                                                                    96
minimum_nights                                                           14
number_of_reviews                                                         0
last_review                                                             NaN
reviews_per_month                                                       NaN
calculated_host_listings_count                                            2
availability_365                                                        178
Name: 14, dtype: object

<p> selecting a single cell</p>

In [32]:
df.at[0,"name"]

'Skylit Midtown Castle'

## BASIC MATH

In [37]:
# up the price by 100
df['new_price'] = df['price'] * 100 # cretaes a new col new_price and has prices * 100 in there
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,new_price
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365,17500
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265,7500
2,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,29,50,2019-12-02,0.37,1,365,6000
3,5136,"Spacious Brooklyn Duplex, Patio + Garden",7378,Rebecca,Brooklyn,Sunset Park,40.66120,-73.99423,Entire home/apt,175,14,1,2014-01-02,0.01,1,295,17500
4,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,65,2,473,2020-03-15,3.44,1,340,6500

In [38]:

cols = ["new_price", "price"]
df[cols]

       new_price  price
0          17500    175
1           7500     75
2           6000     60
3          17500    175
4           6500     65
...          ...    ...
46522      14500    145
46523       8700     87
46524       5900     59
46525       8000     80
46526       6600     66

[46527 rows x 2 columns]

In [ ]:
df['price'].mean()
# average value of the prices

np.float64(148.60566982612247)

calculated col operation:

In [ ]:
df['min_booking_amount'] = df['price'] * df['minimum_nights']
# looks at price col and min nights for every row, multiplies them (vectorized math)
# makes a new col called min_booking amt
df.head(2) # print first 2 rows

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,new_price,min_booking_amount
0,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,175,3,48,2019-11-04,0.37,2,365,17500,525
1,3831,"Whole flr w/private bdrm, bath & kitchen(pls r...",4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,75,1,340,2020-08-01,4.75,1,265,7500,75

In [41]:
cols = ["min_booking_amount", 'price', 'minimum_nights']
df[cols]

       min_booking_amount  price  minimum_nights
0                     525    175               3
1                      75     75               1
2                    1740     60              29
3                    2450    175              14
4                     130     65               2
...                   ...    ...             ...
46522                1015    145               7
46523                 522     87               6
46524                 177     59               3
46525                2400     80              30
46526                  66     66               1

[46527 rows x 3 columns]

- so far the original CSV file hasn't changed due to how Python/Pandas manages RAM
- changes (new cols, math, etc) are being stored in RAM
- when doing pd.read_csv('file_name) a copy is created
- changes apply only to the copy
- since im using a kernel the memory persists as long as the kernal is running
- to make changes i have to write the data to the csv using ".to_csv()" method

## SELECTING & FILTERING DATA